### ISSUE TITLE
Security code page broken when adding a new device (0.15.0)

### ISSUE THREAD

**Issue by Termitebug** [aither64/haveclip-mobile#1]
Hi, as time has passed and things has improved by software updates, the security code page has become a broken feature. Here is a screenshot with a log file.

![screenshot](https://cloud.githubusercontent.com/assets/11379204/20362006/8467adc6-ac42-11e6-8e98-fe85065a37c2.png)

[bug.txt](https://github.com/aither64/haveclip-sailfish/files/595691/bug.txt)

My test setup and both were unpaired in haveclip:
PC: Kubuntu laptop 16.04 64-bit
Device: Jolla 1 Phone SFOS Fiskarsinjoki

**Comment by aither64** [comment]
I'm not sure what it is that is not working for you. I don't see a problem in the screenshot and log that you've provided. You should confirm the security code using the enter key (bottom right corner), not the dialog accept button "Verify", perhaps this is it?

Otherwise please try to tell me what exactly do you expect the program to do and what it does instead.

**Comment by Termitebug** [comment]
It is the enter key nor dialogue button which does nothing, when you enter the correct confirmation code an hit the enter key. Also should the "Verify" change from gray to active color when the security code is correct???


27. Jou 2016 12:17 mennessä notifications@github.com:

**Comment by aither64** [comment]
I see. It is supposed to work like this:

- you type in the security code
- once there are six digits, the enter key becomes active
- when the enter is pressed, the code is sent to the other device, which validates it
- if the code is correct, the "Verify" button will activate and be immediately pressed, closing the dialog
- if the code is not correct, you should see an error

I think the UI could definitely be better, but I'm not sure how to improve it.

Does it work if you initiate the pairing process from Jolla and enter the code on the PC? And clipboard sync then works both ways?

Things to check:
- If there is some trouble on the network, it can take some time before an error is shown, say a minute. I just tested it by blocking haveclip's port on the PC and Jolla behaved the way you say, i.e. tap on the enter key did "nothing", error showed up a minute later. Please check that tcp port 9999 (by default) is not blocked by your firewall (e.g. iptables -L).
- You need to have clipboard receiving enabled (right click on the tray icon on PC, settings on Jolla).
- Check that your certificate in haveclip is still valid, it can be seen in settings (the generated certificates are valid for 10 years, but I'm not sure if it was always like this).

That's all I can think of atm.

**Comment by Termitebug** [comment]
Thanks for step-by-step explanation :+1:
I had a service blocking my 9999 port
Now I feel so embarrassment and a bit shame of not thinking ports first :|
I'm terrible sorry for taking your precious time.
Have a nice day! :)
